// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: Zhaoh0330.proto

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0330Client is the client API for Zhaoh0330 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0330Client interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0330Client struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0330Client(cc grpc.ClientConnInterface) Zhaoh0330Client {
	return &zhaoh0330Client{cc}
}

func (c *zhaoh0330Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0330.sample_package_0330.Zhaoh0330/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0330Server is the server API for Zhaoh0330 service.
// All implementations must embed UnimplementedZhaoh0330Server
// for forward compatibility
type Zhaoh0330Server interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0330Server()
}

// UnimplementedZhaoh0330Server must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0330Server struct {
}

func (UnimplementedZhaoh0330Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedZhaoh0330Server) mustEmbedUnimplementedZhaoh0330Server() {}

// UnsafeZhaoh0330Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0330Server will
// result in compilation errors.
type UnsafeZhaoh0330Server interface {
	mustEmbedUnimplementedZhaoh0330Server()
}

func RegisterZhaoh0330Server(s grpc.ServiceRegistrar, srv Zhaoh0330Server) {
	s.RegisterService(&Zhaoh0330_ServiceDesc, srv)
}

func _Zhaoh0330_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0330Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0330.sample_package_0330.Zhaoh0330/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0330Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0330_ServiceDesc is the grpc.ServiceDesc for Zhaoh0330 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0330_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0330.sample_package_0330.Zhaoh0330",
	HandlerType: (*Zhaoh0330Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Zhaoh0330_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Zhaoh0330.proto",
}
